### ISSUE TITLE
can't build pycltorch with latest distro-cl, pytorch on MacOS 10.11.6

### ISSUE THREAD

**Issue by lebedov** [hughperkins/pycltorch#1]
pycltorch e97efe3 doesn't appear to build against distro-cl 0a1e33d and pytorch a3473d4 on my MacOS 10.11.6 system despite my having successfully installed both of the latter. PyClTorch.pyx appears to need some updates to address changed/missing symbols (e.g., `require` -> `luaRequire`, `pushGlobal` ref missing, etc.) during compilation. Although I was able to get pycltorch to compile and install without error by modifying the include/library paths in `setup.py` and adding several libraries to the list passed to `Extension()` (specifically, lua, luaT, luajit, PyTorch, PyTorchLua, and PyTorchNative), I'm encountering the following exception when I try to run the unit tests.

```
Traceback (most recent call last):
  File "test_cltorch.py", line 2, in <module>
    import PyClTorch
  File "build/bdist.macosx-10.6-x86_64/egg/PyClTorch.py", line 7, in <module>
  File "build/bdist.macosx-10.6-x86_64/egg/PyClTorch.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/lebedov/Library/Caches/Python-Eggs/PyClTorch-0.0.0-py2.7-macosx-10.6-x86_64.egg-tmp/PyClTorch.so, 2): Symbol not found: __Z10luaRequireP9lua_StatePKc
  Referenced from: /Users/lebedov/Library/Caches/Python-Eggs/PyClTorch-0.0.0-py2.7-macosx-10.6-x86_64.egg-tmp/PyClTorch.so
  Expected in: flat namespace
 in /Users/lebedov/Library/Caches/Python-Eggs/PyClTorch-0.0.0-py2.7-macosx-10.6-x86_64.egg-tmp/PyClTorch.so
```

This seems to suggest that the PyClTorch.so extension needs to be dynamically linked against the *.so extensions in PyTorch; however, I'm not sure how to accomplish that. Any thoughts on how I can get the latest revision of pycltorch working? I'm using Python 2.7.12 installed via Anaconda.

**Comment by hughperkins** [comment]
> pycltorch e97efe3 doesn't appear to build against distro-cl 0a1e33d and pytorch a3473d4 on my MacOS 10.11.6 system despite my having successfully installed both of the latter. PyClTorch.pyx appears to need some updates to address changed/missing symbols (e.g., require -> luaRequire, pushGlobal ref missing, etc.) during compilation. Although I was able to get pycltorch to compile and install without error by modifying the include/library paths in setup.py and adding several libraries to the list passed to Extension() (specifically, lua, luaT, luajit, PyTorch, PyTorchLua, and PyTorchNative),

Good point.  Updated, and tested using py3 (I should test on py2.7 too...), on ubuntu.  If you pull down latest pytorch and pycltorch, can you check if it does/doesnt work better now?

(Edit: tested also on py2.7 on ubuntu ,and works ok)

**Comment by hughperkins** [comment]
> This seems to suggest that the PyClTorch.so extension needs to be dynamically linked against the *.so extensions in PyTorch; however, I'm not sure how to accomplish that. Any thoughts on how I can get the latest revision of pycltorch working? I'm using Python 2.7.12 installed via Anaconda.

For this bit, pondering...

**Comment by hughperkins** [comment]
I think I'll try setting up travis mac os x build against pycltorch, and see what happens...

**Comment by lebedov** [comment]
Builds and runs successfully against the `tweak-int` branch of cl-distro/cltorch with Python 2.7.12. Thanks!

**Comment by hughperkins** [comment]
> Builds and runs successfully against the tweak-int branch of cl-distro/cltorch with Python 2.7.12. Thanks!

Ok, you mean, the dynamic linking bit is working ok?

**Comment by lebedov** [comment]
Both the compilation and the dynamic linking appear to be fixed :-) The only item I needed to modify was the location of torch-cl.

**Comment by hughperkins** [comment]
Ah, cool :-)
